[package]
name = "iou-example-project"
version = "0.1.0"
authors = ["michael-grunder <michael.grunder@gmail.com>"]
edition = "2018"

[dependencies]
iou = { git = "https://github.com/withoutboats/iou", branch = "master" }
